### model
model_name_or_path: Qwen/Qwen2.5-VL-72B-Instruct
image_max_pixels: 1000000

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: pc-agent-e
template: qwen2_vl
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: saves/pc-agent-e/Qwen2.5-VL-72B-sft
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 2.0e-6
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
